project_id = "vsjldzfoneoofvntjjcl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[functions.verify-donation]
verify_jwt = false

[functions.livestreams]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.process-bounty-reward]
verify_jwt = true

[functions.charge-bounty-wallet]
verify_jwt = true

[functions.get-email-by-username]
verify_jwt = false

[functions.admin-reset]
verify_jwt = false
