project_id = "vsjldzfoneoofvntjjcl"

[storage]
file_size_limit = "3GB"

[storage.buckets.wutch-videos]
public = true
allowed_mime_types = ["video/mp4", "video/quicktime", "video/x-msvideo", "video/webm"]
file_size_limit = "3GB"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[functions.verify-donation]
verify_jwt = true

[functions.livestreams]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.process-bounty-reward]
verify_jwt = true

[functions.charge-bounty-wallet]
verify_jwt = true

[functions.admin-reset]
verify_jwt = true

[functions.verify-wallet]
verify_jwt = true

[functions.send-email]
verify_jwt = false

[functions.send-password-reset-email]
verify_jwt = false

[functions.request-password-reset]
verify_jwt = false

[functions.send-verification-code]
verify_jwt = true

[functions.verify-and-update]
verify_jwt = true

[functions.process-share-payout]
verify_jwt = true

[functions.admin-grant-badge]
verify_jwt = true

[functions.support-chat]
verify_jwt = false

[functions.generate-cover-image]
verify_jwt = false

[functions.moderate-content]
verify_jwt = true

[functions.mfa-verify]
verify_jwt = true

[functions.x402-verify-payment]
verify_jwt = true

[functions.check-premium-access]
verify_jwt = true

[functions.get-service-orders]
verify_jwt = true

[functions.update-service-order]
verify_jwt = true

[functions.get-creator-wallet]
verify_jwt = false

[functions.x402-verify-payment-v2]
verify_jwt = true

[functions.process-unified-payout]
verify_jwt = true

[functions.register-with-wallet]
verify_jwt = false

[functions.login-with-wallet]
verify_jwt = false

[functions.add-email-to-wallet-account]
verify_jwt = true

[functions.cleanup-ended-streams]
verify_jwt = false

[functions.batch-optimize-videos]
verify_jwt = true
